---
title: Jonas personal blog
description:
email:
baseurl: "/blog"
url: "https://jpeterburs.de"

author: Jonas

social:
  github: jpeterburs
  linkedin: jpeterburs

theme_setting:
  nav_pages:
    - about.md

theme: jekyll-theme-persephone
plugins:
  - jekyll-feed
