---
title: Jonas' CodeCanvas
description: Junior Softwareentwickler aus Kreis Warendorf
email:
baseurl: "/blog"
url: "https://jpeterburs.de"

author: Jonas Peterburs

permalink: /:title

theme_setting:
  nav_pages:
    - about.md

theme: jekyll-theme-persephone
plugins:
  - jekyll-feed
